-- GROUP BY -> É NECESSÁRIO QUE OS REGISTROS SEJAM AGREGAVEIS
-- OU SEJA NÃO SE PODE AGRUPAR REGISTROS COM VALORES DIFERENTES, POR EXEMPLO IDS, QUE CADA UM POSSUI UMA DIFERENTE

SELECT first_name, COUNT(*)  AS total_names FROM users
GROUP BY first_name 
HAVING total_names > 1
ORDER BY total_names DESC;