SELECT RAND(); -- GERA NUMERO ALEATORIO 

SELECT 2+2; -- SQL SUPORTA VISUALIZAÇÃO DE COISAS TRIVIAIS

SELECT RAND() * 1000; -- DA MESMA FORMA QUE SUPORTA OPERAÇÕES MATEMATICAS 

SELECT ROUND(RAND() * 10000, 2); -- ROUND SERVE PARA ARREDONDAR NUMEROS, OS PARAMETROS SÃO ROUND(VALOR, NUMERO DE CASAS DECIMAIS)

-- GERANDO SALARIOS ALEATORIOS NO CAMPO USERS

UPDATE users SET salary = ROUND(RAND() * 1000, 2);
